# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "ok-to-test"

  # Maintain dependencies for go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "ok-to-test"

  # Maintain dependencies for dockerfile in the branches
  - package-ecosystem: docker
    directory: "/build/thirdparty/darwin"
    target-branch: "tools-releases"
    schedule:
      interval: daily
    commit-message:
      prefix: ":seedling:"
  - package-ecosystem: docker
    directory: "/build/thirdparty/linux"
    target-branch: "tools-releases"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"

  # Maintain dependencies for dockerfile scaffold in the projects
  - package-ecosystem: docker
    directory: "testdata/project-v3"
    schedule:
      interval: daily
    commit-message:
      prefix: ":seedling:"
  - package-ecosystem: docker
    directory: "testdata/project-v4"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"

  # Maintain dependencies for go in external plugin sample
  - package-ecosystem: "gomod"
    directory: "docs/book/src/simple-external-plugin-tutorial/testdata/sampleexternalplugin/v1"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "ok-to-test"
