language: go

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

os:
  - linux
  - osx

go:
- "1.12"

env:
  - GOPROXY=https://proxy.golang.org/

git:
  depth: 3

go_import_path: sigs.k8s.io/kubebuilder

services:
- docker

before_install:
# NOTE: The latest version of dep requires go 1.13
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir -p /Users/travis/gopath/bin; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GO111MODULE=on scripts/install_and_setup.sh; fi
- GO111MODULE=on go get sigs.k8s.io/controller-tools/cmd/controller-gen@v0.2.2
- GO111MODULE=on go get sigs.k8s.io/kustomize/kustomize/v3@v3.2.1

before_script:

# Install must be set to prevent default `go get` to run.
# The dependencies have already been vendored by `dep` so
# we don't need to fetch them.
install:
  -

script:
- GO111MODULE=on TRACE=1 ./golden_test.sh
- GO111MODULE=on TRACE=1 ./test.sh
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then GO111MODULE=on TRACE=1 PATH=$PATH:$(pwd) ./test_e2e_v1.sh ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then GO111MODULE=on TRACE=1 PATH=$PATH:$(pwd) ./test_e2e_v2.sh ; fi

# TBD. Suppressing for now.
notifications:
  email: false
