# Uncomment to update deps with dep tool

[prune]
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/emicklei/go-restful"
  revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"

[[constraint]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"

[[constraint]]
  branch = "master"
  name = "github.com/markbates/inflect"

[[constraint]]
  name = "github.com/pkg/errors"
  revision = "a22138067af1c4942683050411a841ade67fe1eb"

[[constraint]]
  name = "github.com/spf13/cobra"
  revision = "f62e98d28ab7ad31d707ba837a966378465c7b57"

[[constraint]]
  version = "kubernetes-1.10.1"
  name = "k8s.io/api"

[[constraint]]
  version = "kubernetes-1.10.1"
  name = "k8s.io/apiextensions-apiserver"

[[constraint]]
  version = "kubernetes-1.10.1"
  name = "k8s.io/apimachinery"

[[constraint]]
  version = "kubernetes-1.10.1"
  name = "k8s.io/apiserver"

[[constraint]]
  version = "kubernetes-1.10.1"
  name = "k8s.io/client-go"
