name: Testdata verification

# Trigger the workflow on pull requests and direct pushes to any branch
on:
  push:
  pull_request:

jobs:

  testdata:
    name: Verify testdata directory
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Clone the code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.21'
      - name: Remove pre-installed kustomize
        # This step is needed as the following one tries to remove
        # kustomize for each test but has no permission to do so
        run: sudo rm -f /usr/local/bin/kustomize
      - name: Verify testdata directory
        run: make check-testdata
      - name: Verify docs update
        run: make check-docs
