name: Testing E2E Sample

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    # Pull requests from the same repository won't trigger this checks as they were already triggered by the push
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '~1.22'

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Create kind cluster
        run: kind create cluster

      - name: Prepare project-v4
        run: |
          KUSTOMIZATION_FILE_PATH="testdata/project-v4/config/default/kustomization.yaml"
          sed -i '25s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '51s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '55,151s/^#//' $KUSTOMIZATION_FILE_PATH
          cd testdata/project-v4/
          go mod tidy

      - name: Testing make test-e2e for project-v4
        working-directory: testdata/project-v4/
        run: |
          make test-e2e

      - name: Teardown kind cluster
        run: kind delete cluster

      - name: Create kind cluster
        run: kind create cluster

      - name: Prepare project-v4-with-plugins
        run: |
          KUSTOMIZATION_FILE_PATH="testdata/project-v4-with-plugins/config/default/kustomization.yaml"
          sed -i '25s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '51s/^#//' $KUSTOMIZATION_FILE_PATH
          # Uncomment only ValidatingWebhookConfiguration
          # from cert-manager replaces
          sed -i '55,70s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '55,70s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '79,101s/^#//' $KUSTOMIZATION_FILE_PATH
          sed -i '110,151s/^#//' $KUSTOMIZATION_FILE_PATH
          # Comment the injection for MutatingWebhookConfiguration
          # Fixme: We should not scaffold or it should be commented
          # by default when only validation webhooks are scaffolded
          WEBHOOK_INJECTION_FILE_PATH="testdata/project-v4-with-plugins/config/default/webhookcainjection_patch.yaml"
          sed -i '3,11s/^/#/' $WEBHOOK_INJECTION_FILE_PATH
          cd testdata/project-v4-with-plugins/
          go mod tidy

      - name: Testing make test-e2e for project-v4-with-plugins
        working-directory: testdata/project-v4-with-plugins
        run: |
          make test-e2e
